name: flutter_smart_generics
description: A collection of reusable generic utilities and widgets to boost productivity and scalability in Flutter development.
version: 1.0.1
homepage: https://github.com/rapzaDev/Flutter-Smart-Generics
repository: https://github.com/rapzaDev/Flutter-Smart-Generics
issue_tracker: https://github.com/rapzaDev/Flutter-Smart-Generics/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
